name: 'CI-dev'

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: dev
      TF_VAR_project_id: ${{ vars.DEV_PROJECT_ID }}
      TF_VAR_region: ${{ vars.DEV_REGION }}
      TF_VAR_zone: ${{ VARS.DEV_ZONE }}
      TF_VAR_bucket_name: ${{ vars.DEV_BUCKET_NAME }}
      TF_VAR_project_name: ${{ vars.DEV_project_name }}
      TF_VAR_db_tier: ${{ vars.DEV_DB_TIER }}
      TF_VAR_db_name: ${{ vars.DEV_DB_NAME }}
      TF_VAR_db_user: ${{ vars.DEV_DB_USER }}
      TF_VAR_db_password: ${{ secrets.DEV_DB_PASSWORD }}
      TF_VAR_secret_key: ${{ secrets.DEV_SECRET_KEY }}
      # GOOGLE_CREDENTIALS: ${{ secrets.DEV_GOOGLE_CREDENTIALS }} 


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
          workload_identity_provider: 'projects/592177197716/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account:  'github-actions-sa@pbl6-439109.iam.gserviceaccount.com'

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      # env:
        # GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -out .planfile         
      # env:
      #   GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
        
    - name: Post PR comment
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        planfile: .planfile